### ISSUE TITLE
FAQ "Breeding mechanics have been ported from Emerald," - Volt Tackle

### ISSUE THREAD

**Issue by QuickBASIC** [Deokishisu/FRLG-Plus#11]
The [FAQ](https://github.com/Deokishisu/FRLG-Plus/blob/bff5bda749f67832f4522c88946f304c0b434aec/FAQ.md#L11) isn't clear that special cases like Volt Tackle haven't been ported from Emerald (Pikachu holding a Light Ball). This may have been a design decision based on your goals for this project, but I suggest either updating FAQ or including the special cases in the breeding mechanics you've ported. 

Reference:
https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_breeding
https://github.com/pret/pokeemerald/blob/e0fae879da1b773bf90fca145e047ccdb7613938/src/daycare.c#L753

**Comment by Deokishisu** [comment]
You're correct that that should be added to the FAQ. Any Volt Tackle Pichu/Pikachu/Raichu generated outside of Emerald or events is illegal, so that's why Volt Tackle breeding was intentionally left out. I'll update the FAQ in the next commit. Thank you.
