### ISSUE TITLE
QoL -  Add option to take held item from newly obtained Pokémon when sending to PC storage

### ISSUE THREAD

**Issue by 00mn00** [Deokishisu/FRLG-Plus#14]
I ported these commits from https://github.com/citrusbolt/pokeheliodor/commit/d78b47dcbfcf4d3dc775eae9c3a36a34e461269e / https://github.com/citrusbolt/pokeheliodor/commit/830d0d43729a559a9e27f222ccdbfb371bb06493 and have tested them to the best of my ability working without issue. Would you like me to open a pull request with the code, so it can be merged, or is this outside of the scope of what you think is appropriate for your project?

**Comment by 00mn00** [comment]
I've also exposed Nature Power/Weather Ball in battle and the summary screen with no issues from what I can tell. Since I was the one who asked for it to be done, I'm happy to send the code across for this as well.

**Comment by Deokishisu** [comment]
For the Heliodor feature, could I get a gif of it in action? I don't play other people's hacks.

Please link your commit with the Weather Ball change and I'll take a look at it. The Nature Power one is fine if that doesn't have any issues.

I'm not actively working on this or any project at the moment, so it may be a few weeks before I actually accept PRs or comb through commits.

**Comment by 00mn00** [comment]
I've posted the commits for Weather Ball and Nature Power. No rush on going through the code, we all have busy lives. I'll update this post with a video or GIF as you requested later on today, hopefully.

**Comment by Deokishisu** [comment]
Nature Power and Weather Ball are exposed in the latest release. I'm pretty on the fence about the held item option, leaning towards no. I'm going to close this for now and reconsider for a future release.
