### ISSUE TITLE
[QoL Request] Disable Bag in Trainer Battles

### ISSUE THREAD

**Issue by k138z** [Deokishisu/FRLG-Plus#17]
Right now it is easy to self-impose this though.

**Comment by 00mn00** [comment]
I did something similar to this on my fork - https://github.com/00mn00/FRLG-Plus_Custom/tree/key_system_setting_changes - you're welcome to look at the code and implement it yourself, it's really not that difficult.

**Comment by Deokishisu** [comment]
Because this is so easy to self-impose without having to meticulously track anything or modify the game in any way, I prefer to leave this up to the player.
