### ISSUE TITLE
[bug] Frozen pokemon can flee

### ISSUE THREAD

**Issue by anzz1** [Deokishisu/FRLG-Plus#20]
This happened while encountering the first legendary beast (Suicune) in the Kanto overworld. I do not know if the bug is special to this case or applies to any wild pokemon. I do have a save state though where I can reliably recreate the bug.

1. While surfing next to Cerulean Cave, Suicune encounter starts.
2. At first turn, Used Ice Beam on Suicune, I have the first hit.
3. Suicune is frozen solid.
4. Suicune has fled.

**Comment by anzz1** [comment]
I can make a video clip or post the save state file if need to be.

**Comment by Deokishisu** [comment]
This is a vanilla Gen 3 behavior. Roamers in Gen 3 can flee regardless of their status condition.
