### ISSUE TITLE
[feature request] Battle Tower "151 / Gen1 Mode"

### ISSUE THREAD

**Issue by anzz1** [Deokishisu/FRLG-Plus#21]
I've been thoroughly enjoying this mod so far, and I especially like the Battle Tower addition for a thing to do after completing the main story (and I haven't even discovered everything yet). 

I do have a request though, as I suppose the enemy trainer parties in the tower are lifted from a table or randomly generated, to add a "151 mode" / "Gen1 mode" / "OG mode" / "Kanto mode" or whatever you want to call it, which would only allow the OG 151 pokemon to be used in battles. This probably wouldn't be too hard to add, limiting only the usable pokemon and not their movesets. 

I think the Gen2 evolutions of Gen1 pokemon could be allowed too, making it a "151+ mode" or "Kanto mode" ("Only species of Kanto origin are allowed") or something like that, as it could be seen as too restricting to not let player use some mon he caught in Kanto and evolved it, only to discover in the lategame that he can't use it in this mode. That's only my opinion though, a "pure" 151 mode would also do.

**Comment by Deokishisu** [comment]
I agree with you that "themed" modes similar to some of the old VGC tournaments could be a cool mechanic, but I feel it is out of scope for something like FRLG+. Neither Emerald nor RS did something like that with its facilities, and FRLG+ is meant to slot in with the other Gen 3 games.

I may revisit this idea in the future with a future project, however. Thanks for the suggestion.
