### ISSUE TITLE
[bug] EV/IV calc keysetting is ignored in Battle Tower

### ISSUE THREAD

**Issue by anzz1** [Deokishisu/FRLG-Plus#22]
In function `void CreateBattleTowerMon(struct Pokemon *mon, struct BattleTowerPokemon *src)` the `calcOverride` flag of `void CalculateMonStats(struct Pokemon *mon, bool8 calcOverride)` is set to TRUE, thus ignoring the keysetting of IV/EV calculation. This means putting the player at serious disadvantage if playing in IV zero or EV zero modes. If this is intended behaviour, it is not noted anywhere.

https://github.com/Deokishisu/FRLG-Plus/blob/master/src/pokemon.c#L3268

**Comment by anzz1** [comment]
Or is this a case of me just missing something, that the CreateBattleTowerMon only affects the party creation and the calcOverride flag is later honored in the battle itself?

**Comment by Deokishisu** [comment]
The Battle Tower (and link rooms) *should* specifically ignore the stat calc keys and do vanilla stat calc battles. I justified this in the Battle Tower due to the ribbons they give (which are tradeable and can be transferred up), so I wanted to preserve the original challenge for earning them.
