### ISSUE TITLE
Altering Cave

### ISSUE THREAD

**Issue by Zelly9191** [Deokishisu/FRLG-Plus#27]
I have a suggestion would it be possible to change the script of the altering cave so that when you enter it picks a random value between 1-10 and loads the corresponding encounter table? I know it's possible to do with binary hacking. 

Better yet maybe you could make it so every time you enter the cave It increments the value by one and then when it reaches 10 it loops back to 1 again This would make it so you have access to every single encounter table in the altering cave.

That way the other nine encounter tables don't go to waste. I think this would be really cool and I'm pretty sure the pokémon are legal.

:)

**Comment by anzz1** [comment]
try this #26

**Comment by Zelly9191** [comment]
hey thank you so much ill be sure to try this out

**Comment by Deokishisu** [comment]
The extra Altering Cave Pokemon are technically illegal in Gen 3 since they were never released. Since this hack strives to make all obtainable Pokemon legal in Gen 3, Altering Cave will remain a Zubat-only cave.
