### ISSUE TITLE
Corsola though on the extended Pokedex has area unknown in both versions 

### ISSUE THREAD

**Issue by BasileiatonRhomaion** [Deokishisu/FRLG-Plus#30]
Alright so I remember that the extended Pokedex your able to catch all 246 Pokemon that are apart of the extended Pokedex but Corsola is labled as having no area whatsoever in both versions.

**Comment by Deokishisu** [comment]
Corsola is only available as a gift Pokemon and therefore will not show up in the area indicator of the Pokedex.
