### ISSUE TITLE
Gym Leader Rematches Location Post-FameChecker Empty

### ISSUE THREAD

**Issue by bmetenko** [Deokishisu/FRLG-Plus#31]
Completed all fame checker unlocks and waited for spearow for all 8 gym leaders, but rematch room has been empty since I had lost to brock initially. Is this intended behavior? If not, can I fix this manually?

**Comment by Deokishisu** [comment]
https://github.com/Deokishisu/FRLG-Plus/blob/master/FAQ.md#how-does-inviting-a-gym-leader-work-a-gym-leader-i-invited-is-gone-when-is-the-rematch-ladys-spearow-coming-back
