### ISSUE TITLE
Repel Not Working as Intended in Power Plant

### ISSUE THREAD

**Issue by RbtsEvrwhr-Riley** [Deokishisu/FRLG-Plus#36]
Not sure if this is happening in other areas.

Use Repel with a level 33 or 35 pokemon in the lead in Power Plant. You will get encounters as if you do not have a Repel, including a Level 23 pikachu.

**Comment by Deokishisu** [comment]
Was Nuzlocke Mode enabled and, if so, did you already have your first encounter in the Power Plant?

With Nuzlocke Mode on, Repels don't work for the first encounter in an area. Repels will work normally after the first encounter.
