### ISSUE TITLE
Cerulean Cave - STUCK!

### ISSUE THREAD

**Issue by crz4all** [Deokishisu/FRLG-Plus#4]
The location has a serious bug, if you don't have an Escape Rope, Dig or Teleport, you will be stuck in that location forever. One of the stairs has no exit script.

**Comment by Deokishisu** [comment]
Could you attach a screenshot of the faulty stairs? I did find an error in one of the Cerulean Cave layouts, but not one that would trap the player.

I don't see any stairs that don't have exits, but I may have missed it.

**Comment by crz4all** [comment]
See the vídeo.
https://www.youtube.com/watch?v=VmSacYhd1Tc

**Comment by Deokishisu** [comment]
Thank you for the additional info. This has been fixed by 2f762d203e6a923835831a6dd87ef5a89920f715 which will be included in the next release.

If you are currently trapped, white out to the wild Pokemon.
