### ISSUE TITLE
Unable to patch an EU version of the game

### ISSUE THREAD

**Issue by youdontknowmu** [Deokishisu/FRLG-Plus#42]
Hello there,

Is there any way to use this patch on a EU verison of the game ? I'm looking to make my 7y old to play this rom but he only knows french :D

Thanks a lot for the suggestions

**Comment by Deokishisu** [comment]
Unfortunately, that's not how patches like these work. This was built on the English ROM and there's no way to, for example, selectively apply my changes to the French ROM while keeping the French text. I'm going to close this issue.
