### ISSUE TITLE
Saving after Link Battles corrupts item data

### ISSUE THREAD

**Issue by TetsuyaGR** [Deokishisu/FRLG-Plus#6]
Steps to reproduce:

1. Link with another FRLG+ and do a battle (You can also just Run for a quick Draw)
2. After the battle finishes it autosaves
3. Check your bag, it affects specifically the expanded slots Medicine and Held Items
4. ???
5. Profit infinite items

No cheats ever used and i tested it with 2 different emulators (VBALink 1.8 for PC and PizzaBoy GBA Pro for Android)

Proof:
<p float="left">
  <img src="https://user-images.githubusercontent.com/48888784/159165568-2fe0b780-f115-4f2d-a283-c89e020e21fa.png" />
  <img src="https://user-images.githubusercontent.com/48888784/159165575-c0b19706-7a64-4927-baf0-dd54dc12fcad.png" /> 
</p>

**Comment by TetsuyaGR** [comment]
Probably the issue stems from here, not sure though
https://github.com/Deokishisu/FRLG-Plus/blob/2f762d203e6a923835831a6dd87ef5a89920f715/src/save.c#L667-L671

**Comment by Deokishisu** [comment]
Thanks for your report! I'll look into this and fix it for the next release.
