### ISSUE TITLE
Add level limit

### ISSUE THREAD

**Issue by Mathynnn** [Deokishisu/FRLG-Plus#8]
Hi,

Thanks for your project. I really like it.
I'm curious if you want to add a Level Limit to the system.

I really like to not overlevel my pokemon when facing a gym. 

Thanks!

**Comment by Deokishisu** [comment]
I won't be implementing a level limit feature, but you can prevent all Pokemon from gaining experience by setting the Exp Mod key in the Key System Menu to 0x. This way, you can train your team up to the level limit and then turn off experience gain until you are ready to turn it back on.

Thank you for your feedback.

**Comment by anzz1** [comment]
@Mathynnn 
The level limit option has been implemented in QoL patch v1: #26
