### ISSUE TITLE
Physical/Special Split

### ISSUE THREAD

**Issue by CWSpear** [Deokishisu/FRLG-Plus#9]
Would it be possible/worthwhile to get a physical/special split for moves like introduced in Gen 4 and on?

I realize this may be rather complicated as not only would you have to add those values to every ability, you'd have to update any code that uses its (e.g. grass) type to determine its (e.g. special) category.

You'd probably want to introduce the additional moves and update the pokemon that use them: for example, adding Giga Impact and replacing Hyper Beam on certain Pokemon.

**Comment by Deokishisu** [comment]
As I have said multiple times both in the PokeCommunity thread and in the features list, this hack aims to maintain *full* compatibility with the vanilla games and to maintain the vanilla flavor. The physical/special split both makes link battles with vanilla a no go and ruins the original flavor of the battle mechanics.

So no, the physical/special split will not be implemented.

**Comment by CWSpear** [comment]
Figured it'd been discussed somewhere and I just didn't see! Thanks for the reply and sorry for duplicate questions. :)
